update some files

diff --git a/.github/workflows/laravel.yml b/.github/workflows/laravel.yml
--- a/.github/workflows/laravel.yml
+++ b/.github/workflows/laravel.yml
@@ -21,7 +21,11 @@ jobs:
       repository-projects: write
 
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Install jq
+        run: sudo apt-get install -y jq
 
       - name: Set up PHP
         uses: shivammathur/setup-php@v2
@@ -34,23 +38,17 @@ jobs:
       - name: Install Dependencies
         run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
 
-      - name: Directory Permissions
-        run: chmod -R 777 storage bootstrap/cache
+      - name: Build assets with Vite
+        run: npm install && npm run build
 
       - name: Generate key for PHPUnit/Pest
         run: php artisan key:generate --env=testing
-
-      - name: Build assets with Vite
-        run: npm install && npm run build  # Assurez-vous que Vite est correctement configuré pour votre application
 
       - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
         env:
           DB_CONNECTION: sqlite
           DB_DATABASE: ':memory:'  # Utilisation de SQLite en mémoire
         run: php artisan test --log-junit tests/results.xml
-
-      - name: Install jq
-        run: sudo apt-get install -y jq
 
       - name: Upload test results
         uses: actions/upload-artifact@v2
@@ -70,27 +68,26 @@ jobs:
         id: extract_test_info
         run: |
           PASS=$(grep -oP '<testsuites tests="\K\d+' tests/results.xml || echo "0")
-          TODO=$(grep -oP '(?<=<testsuite name=".*" tests="\d+" skipped=")\d+' tests/results.xml | awk '{s+=$1} END {print s}' || echo "0")
-          SKIP=$(grep -oP '(?<=<testsuite name=".*" tests="\d+" skipped="0" errors="0" failures="0" timestamp=").*(?=" time=)' tests/results.xml | wc -l || echo "0")
-          echo "PASS: $PASS"
-          echo "TODO: $TODO"
-          echo "SKIP: $SKIP"
+          FAILURES=$(grep -oP '<testsuites failures="\K\d+' tests/results.xml || echo "0")
+          TOTAL=$(grep -oP '<testsuites tests="\K\d+' tests/results.xml | head -n 1 || echo "0")
+          echo "::set-output name=pass::$PASS"
+          echo "::set-output name=failures::$FAILURES"
+          echo "::set-output name=total::$TOTAL
 
       - name: Update README with Badge URLs
         run: |
           PASS=${{ steps.extract_test_info.outputs.pass }}
-          TODO=${{ steps.extract_test_info.outputs.todo }}
-          SKIP=${{ steps.extract_test_info.outputs.skip }}
+          FAILURES=${{ steps.extract_test_info.outputs.failures }}
+          TOTAL=${{ steps.extract_test_info.outputs.total }}
           sed -i "s|!\[Tests Passed\](.*)|![Tests Passed](https://img.shields.io/badge/tests_passed-${PASS}-brightgreen?style=flat-square)|g" README.md
-          sed -i "s|!\[Tests TODO\](.*)|![Tests TODO](https://img.shields.io/badge/tests_todo-${TODO}-yellow?style=flat-square)|g" README.md
-          sed -i "s|!\[Tests Skipped\](.*)|![Tests Skipped](https://img.shields.io/badge/tests_skip-${SKIP}-lightgrey?style=flat-square)|g" README.md
+          sed -i "s|!\[Tests Failed\](.*)|![Tests Failed](https://img.shields.io/badge/tests_failed-${FAILURES}-red?style=flat-square)|g" README.md
+          sed -i "s|!\[Tests Total\](.*)|![Tests Total](https://img.shields.io/badge/tests_total-${TOTAL}-blue?style=flat-square)|g" README.md
 
       - name: Commit and push updated README
         if: ${{ github.event_name == 'push' }}
         run: |
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"
-          git add tests/results.xml
           git add README.md
           git commit -m "Update README with test badges"
-          git push origin HEAD:refs/heads/dev
+          git push origin HEAD:main
